### ISSUE TITLE
Import CI very short

### ISSUE THREAD

**Issue by redfish8** [InfotelGLPI/cmdb#9]
Hello,
I give a try to the CMDb plugin but hit a problem, when I create a new CI and wish to import from GLPI items my list is very limited
![image](https://user-images.githubusercontent.com/98093377/152943639-9a370056-078d-4d40-93a1-8c92595a46ca.png)
I guess I missed one step during setup, can you help me ?

GLPI 9.5.6

**Comment by tsmr** [comment]
Hello

The others item type are available into setup > General > Impact analysis

**Comment by redfish8** [comment]
OK found them I'll try to find my way to setup correctly this plugin.
Thank you
